name: 'Che Plugin Updater'
description: 'Github Action to automatically update and maintain a section of the Che Plugin Registry'
author: 'JPinkney'
inputs:
  pluginPath:
    required: true
    description: 'The name of the organization and the plugin in the Che Plugin Registry. E.g. redhat-developer/vscode-yaml'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
